version: "3"
services:
  db-master:
    build: 
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db-master'
      MYSQL_USER: 'yb'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    # Where our data will be persisted
    volumes:
      - ~/yb/docker-volume/mysql-replication/master:/var/lib/mysql
      - ~/yb/docker-volume/mysql-replication/master-files:/var/lib/mysql-files
    networks:
      - net-mysql
  
  db-slave:
    build: 
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'db-slave'
      MYSQL_USER: 'yb'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - ~/yb/docker-volume/mysql-replication/slave:/var/lib/mysql
      - ~/yb/docker-volume/mysql-replication/slave-files:/var/lib/mysql-files
    networks:
      - net-mysql
  
# Names our volume

networks: 
  net-mysql:
    driver: bridge